# Generated by Django 5.0.6 on 2024-08-06 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uder',
            new_name='user',
        ),
    ]
